name: flutter_navigator
description: " Flutter package for simplified page-to-page navigation."
version: 0.0.1
homepage: https://github.com/Suneel-DK/flutter_navigator

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

